#!/bin/bash
#
# simple script to grab the latest heroku backup from heroku

function get_backup_id {
  local backups

  heroku pg:backups capture
  backups=$(heroku pg:backups)
  if [ "$?" -ne 0 ]; then
    exit 1
  fi

  backup_id=$(echo "$backups" | head -4 | tail -1 | cut -d' ' -f1)
}

function copy_backup_file {
  local dir="${1:?missing directory name}"
  local id="${2:?missing backup file id}"
  local backup_file="$backup_dir/$backup_id"

  echo "Loading latest backup into $backup_file"
  curl -o "$backup_file" $(heroku pg:backups public-url $backup_id)
}

backup_dir=database-backups
backup_id=""

get_backup_id
copy_backup_file "$backup_dir" "$backup_id"
